### ISSUE TITLE
Handlebars

### ISSUE THREAD

**Issue by AlexEBall** [AlexEBall/physicalWebMuseum#10]

**Comment by MJOAN** [comment]
We should have 'exhibit' handlebar templates for: 

1. artist name
2. title
3. description
4. medium
5. created date

then we could include:

1. exhibit location, gift shop, further artist information 
2. artist personal website, artist purchasing page if they want to buy
3. artist and or exhibit social media pages

**Comment by MJOAN** [comment]
Wanted to add the signup and login handlebars with js files to master branch as well.
