### ISSUE TITLE
Beacons

### ISSUE THREAD

**Issue by AlexEBall** [AlexEBall/physicalWebMuseum#15]

**Comment by MJOAN** [comment]
Hi Alex, Found this: https://accent-systems.com/wp-content/uploads/iBKS105_datasheet_rev3.pdf on page 8 shows chart of power(dBm)/distance(m).  

Also: here: https://resources.beaconstac.com/ebook/the-definitive-guide-to-beacon-pilots-11082017.pdf?__s=eu6sdmxdznxx51shoqur page 32 talks about beacon set in museum.  Got an idea we could include "further information" section in handlebars so attendees can click through to the exhibitor's main page, audio links or the gift shop to purchase.

1. Check exact beacon location, signal strength and density.
2. Keep map of every beacon [major/minor] numbers to track
3. Create "notification" for user - maybe we can add audio links here too? 
4. Create "rule" for proximity - if we can!
